import pandas as pd
import matplotlib.pyplot  as plt
df=pd.read_csv("retail.csv")
print(df.head())
df=df.drop_duplicates(subset="Customer_Name")
df["Customer_Name"]=df["Customer_Name"].fillna("raju")
print(df)
total=df.Total_Sales.sum()
print("total sales",total)
region=df.Region.count()
print("how many region",region)
print(df[df.Total_Sales>100])
minimum=df["Total_Sales"].min()
print("minimum sales:",minimum)
maxi=df["Total_Sales"].max()
print("minimum sales:",maxi)
df["Region"] = df["Region"].str.strip().str.title()
sales_region = df.groupby("Region")["Total_Sales"].sum()
plt.figure(figsize=(12, 12))
plt.subplot(2, 3, 1)
sales_region.plot(kind="bar")
plt.title("Sales by Region")
plt.xlabel("Region")
plt.ylabel("Sales")

payment_counts = df["Payment_Method"].value_counts()
sizes = payment_counts.values
labels = payment_counts.index
plt.subplot(2,3,3)
plt.pie(sizes,labels=labels,startangle=90,autopct="%1.1f%%",labeldistance=1.15,pctdistance=0.7)
plt.title("Payment Method Distribution")
df["Order_Date"] = pd.to_datetime(df["Order_Date"],format="mixed")
monthly_sales = df.groupby(df["Order_Date"].dt.month)["Total_Sales"].sum()
plt.subplot(2, 3, 5)
monthly_sales.plot(kind="line", marker="o")
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()
